server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:default}"
  config:
    import: "optional:configserver:${SPRING_CONFIG_IMPORT:http://localhost:8071/}"

  datasource:
    url: jdbc:h2:mem:accounts
    driver-class-name: org.h2.Driver
    username: sa
    password: sc
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include:
          - "busrefresh" # include: "health, info, refresh"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
