server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:default}"

  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/accountsdb}"
    username: "${SPRING_DATASOURCE_USERNAME:root}"
    password: "${SPRING_DATASOURCE_PASSWORD:root}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  sql:
    init:
      mode: always
  config:
    import: "configserver:${SPRING_CONFIG_IMPORT:http://localhost:8071/}"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true



#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "metrics"
          - "circuitbreakers"
          - "prometheus"
          # include: "health, info, refresh"d
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


springdoc:
  swagger-ui:
    path: /swagger-ui.html

info:
  app:
    name: "accounts"
    description: "Bank Account application"
    version: "1.0.0"

eureka:
  instance:
    prefer-ip-address: true # register with the ip number
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE:http://localhost:8070/eureka/}"

logging:
  level:
    com:
      bank:
        accounts: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException








