server:
  port: 8082

spring:
  application:
    name: cards

  datasource:
    url: jdbc:h2:mem:carddb
    driver-class-name: org.h2.Driver
    username: sa
    password: sc
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html