server:
  port: 8082

spring:
  application:
    name: "cards"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:default}"

  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/cardsdb}"
    username: "${SPRING_DATASOURCE_USERNAME:root}"
    password: "${SPRING_DATASOURCE_PASSWORD:root}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  sql:
    init:
      mode: always

  config:
    import: "configserver:${SPRING_CONFIG_IMPORT:http://localhost:8071/}"


#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"