build:
  version: "1.0"

loans:
  message: "Welcome to Bank cards related QA APIs"
  contactDetails:
    name: "juan david"
    email: "qa@juandavyc.com"
  onCallSupport:
    - (57) 300-000-0000
    - (57) 300-000-0000