server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/juandavyc/spring-boot-3-cloud-configs-bank.git
          timeout: 5
          clone-on-start: true
          force-pull: true
          default-label: main
#  rabbitmq:
#    host: localhost
#    username: guest
#    password: guest
#    port: 5672

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - monitor
          - busrefresh
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true
