server:
  port: 8081
spring:
  application:
    name: "loans"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:default}"

  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/loansdb}"
    username: "${SPRING_DATASOURCE_USERNAME:root}"
    password: "${SPRING_DATASOURCE_PASSWORD:root}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: "configserver:${SPRING_CONFIG_IMPORT:http://localhost:8071/}"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include:
          - "busrefresh"
          - "info"
          - "shutdown"
  endpoint:
    shutdown:
      access: unrestricted

  info:
    env:
      enabled: true

info:
  app:
    name: "loans"
    description: "Bank Loans Microservice"
    version: "1.0.0"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE:http://localhost:8070/eureka/}"


