server:
  port: 8070
spring:
  application:
    name: "eurekaserver"
  config:
    import: "configserver:${SPRING_CONFIG_IMPORT:http://localhost:8071/}"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"