server:
  port: 8081
spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:loansdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  profiles:
    active:
      - "qa"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

build:
  version: "1.0"

loans:
  message: "Welcome to Bank loans related DEV APIs"
  contactDetails:
    name: "juan david"
    email: "dev@juandavyc.com"
  onCallSupport:
    - (57) 300-000-0000
    - (57) 300-000-0000