services:
  accounts:
    image: "juandavyc/accounts:s4"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  loans:
    image: "juandavyc/loans:s4"
    container_name: lohans_ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  cards:
    image: "juandavyc/cards:latest"
    container_name: cards_ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
networks:
    bank:
      driver: "bridge"
