build:
  version: "3.0"

cards:
  message: "Welcome to Bank cards related DEV APIs"
  contactDetails:
    name: "juan david"
    email: "dev@juandavyc.com"
  onCallSupport:
    - (57) 300-000-0000
    - (57) 300-000-0000